# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1db62203afffbd286585f5a0f6d86951318ff15d0ea8a1c8523d79ff1afc5ca0ef22df35b0a9ba77aa498b7c75108bfa0d498c34eedf8d9795bb27db114c9e

test:
  secret_key_base: 9b2179cf78f2095cadc4555ed48ed74cafbf30711871ddd95db6599db0f2a821fc7388917f0580872fad7ec290dcd9dddc5404635067686f45cbce9f01f0fd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
